service: live-20-cognito
frameworkVersion: '3'

plugins:
  - serverless-esbuild

package:
  individually: true

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  deploymentMethod: direct
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action: cognito-idp:AdminGetUser
          Resource: !GetAtt Live020UserPool.Arn
  environment:
    COGNITO_CLIENT_ID: !Ref LiveUserPoolClient
    COGNITO_POOL_ID: !Ref Live020UserPool
  httpApi:
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt Live020UserPool.ProviderURL
        audience:
          - !Ref LiveUserPoolClient

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node20
    exclude:
      - '@aws-sdk/*'
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10

resources:
  Resources:
    Live020UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        DeletionProtection: INACTIVE
        UserPoolName: Live020UserPool
        MfaConfiguration: OFF
        AutoVerifiedAttributes:
          - email
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        UsernameAttributes:
          - email
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: "verified_email"
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLength: 10
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
            TemporaryPasswordValidityDays: 2
        Schema:
          - Name: given_name
            Mutable: true
            Required: true
            AttributeDataType: String
          - Name: family_name
            Mutable: true
            Required: true
            AttributeDataType: String
    LiveUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: LiveUserPoolClient
        UserPoolId: !Ref Live020UserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        TokenValidityUnits:
          AccessToken: hours
          RefreshToken: hours
        AccessTokenValidity: 3
        RefreshTokenValidity: 1440 # 60 days

functions:
  cognitoCustomMessage:
    handler: src/functions/cognitoCustomMessage.handler
    events:
      - cognitoUserPool:
          pool: Live020UserPool
          trigger: CustomMessage
          existing: true
          forceDeploy: true

  signUp:
    handler: src/functions/signUp.handler
    events:
      - httpApi:
          method: POST
          path: /auth/sign-up
  accountConfirmation:
    handler: src/functions/accountConfirmation.handler
    events:
      - httpApi:
          method: POST
          path: /auth/account-confirmation
  signIn:
    handler: src/functions/signIn.handler
    events:
      - httpApi:
          method: POST
          path: /auth/sign-in
  refreshToken:
    handler: src/functions/refreshToken.handler
    events:
      - httpApi:
          method: POST
          path: /auth/refresh-token
  forgotPassword:
    handler: src/functions/forgotPassword.handler
    events:
      - httpApi:
          method: POST
          path: /auth/forgot-password
  resetPassword:
    handler: src/functions/resetPassword.handler
    events:
      - httpApi:
          method: POST
          path: /auth/reset-password
  profile:
    handler: src/functions/profile.handler
    events:
      - httpApi:
          method: GET
          path: /profile
          authorizer:
            name: CognitoAuthorizer
